version: '3'

vars:
  UPDATE_PROMPT: |
    It will update the modpack. Do not forget to change version in
    the pack.toml file if any changes are made! Continue?

tasks:
  server:index:
    desc: Refresh the index of server modpack
    dir: server/
    cmds:
      - '{{ .ROOT_DIR }}/bin/packwiz refresh'

  server:update:
    desc: Update the server modpack
    prompt: '{{ .UPDATE_PROMPT }}'
    dir: server/
    cmds:
      - '{{ .ROOT_DIR }}/bin/packwiz update --all'
      - task: server:index
