name = "dungeon-heroes"
author = "iveahugeship"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7a572b03581a401cd563bd13ba641f4c00eb0866deb1c2c1983d97d1fa5dc49"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
