name = "talescrafters"
author = "iveahugeship"
version = "0.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35f51e59c0f70f16bb03d5036977f98ae64cea32d3a79e7eae2e21c7bdaefcbd"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
