name = "tales-craft"
author = "iveahugeship"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f8745597f0b170ac84e2eb8864d499e6b73133d8c291e477532728da0983a12"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
