name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - "modpack/**"
    tags:
    - "v*"

jobs:
  build-modrinth:
    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Environment
      run: |
        cp "bin/packwiz-$(uname -m)" bin/packwiz && \
        echo "$PWD/bin" >> "$GITHUB_PATH"

    - name: Build Artifact
      working-directory: modpack/
      run: |
        packwiz modrinth export

    - name: Upload Artifact
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: talescrafters-modrinth
        path: "modpack/talescrafters-*.mrpack"

  build-curseforge:
    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Environment
      run: |
        cp "bin/packwiz-$(uname -m)" bin/packwiz && \
        echo "$PWD/bin" >> "$GITHUB_PATH"

    - name: Build Artifact
      working-directory: modpack/
      run: |
        packwiz curseforge export

    - name: Upload Artifact
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: talescrafters-curseforge
        path: "modpack/talescrafters-*.zip"

  release:
    if: github.ref_type == 'tag'
    needs:
    - build-modrinth
    - build-curseforge
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v5
      with:
        artifact-ids: ${{ needs.build-modrinth.outputs.artifact-id }},${{ needs.build-curseforge.outputs.artifact-id }}
        merge-multiple: true

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "talescrafters-*"
